### ISSUE TITLE
jpm local build doesn't work

### ISSUE THREAD

**Issue by kodiak22** [janet-lang/jpm#18]
janet-lang version: 1.7.1
jpm version: commit=cf6086a
Installed from the arch linux aur repo: https://aur.archlinux.org/packages/janet-lang/

I have a small project that uses spork/argparse.
According to the docs this should work if I'm in the project directory:
$ jpm -l deps    [OK] dependencies are installed in $project_dir/jpm_tree/lib/
$ jpm -l build
generating executable c source build/gc-janet.c from main.janet...
error: could not find module spork/argparse:
    /usr/lib/janet/spork/argparse.jimage
    /usr/lib/janet/spork/argparse.janet
    /usr/lib/janet/spork/argparse/init.janet
    /usr/lib/janet/spork/argparse.so

**Comment by sogaiu** [comment]
There have been some commits since cf6086a for jpm.

Do you get the same issue for the latest master (c2be9143201154c2b068f954474f1e0983f81189)?

**Comment by kodiak22** [comment]
Hi sogaiu,
I've hacked the aur package to install jpm from the current master and still doesn't work,
with another error, it doesn't find janet.h which is under /usr/include/janet/.
If janet and jpm is installed through their own respective install commands (sudo make install & sudo janet bootstrap.janet) under /usr/local/ then my project builds without error.
So probably there are problems with the AUR package, I will try to find out what.
Anyway, I'm closing this issue.
Thanks.

**Comment by sogaiu** [comment]
@kodiak22 Thanks for trying and reporting back.
