### ISSUE TITLE
jpm build + jaylib => functions are nil

### ISSUE THREAD

**Issue by saikyun** [janet-lang/jpm#2]
When running `jpm build && ./build/lul` in this minimal project: https://github.com/saikyun/jaylib-and-new-jpm-test

Source (UPDATED to use `jaylib` instead):
```
(use jaylib)

(defn main [& args]
  (init-window 800 600 "wat")
  (pp args)
  (print "hej :)"))
```

I get:
```
error: nil called with 3 arguments, possibly expected 1
  in main [lul/main.janet] on line 4, column 3
```

It works when doing `janet lul/main.janet`.

Am on Ubuntu, `janet 1.17.0-dev-61769c8f linux/x64`.

**Comment by bakpakin** [comment]
Looks like the `init-window` function call is somehow not being loaded or linked, and is instead replaced with nil.

**Comment by saikyun** [comment]
It happened to all functions I tried. Any clue where to start checking?

Den tis 3 aug. 2021 17:47Calvin Rose ***@***.***> skrev:

**Comment by saikyun** [comment]
I had accidentally written `(use freja-jaylib)` when I made the repro repo. I've now updated it, and I still get the same error.

**Comment by saikyun** [comment]
Another error, with the following source:
```
(defn main [& args]
  (require "jaylib"))
```
I get:
```
error: could not load native /usr/local/lib/janet/jaylib.so: /usr/local/lib/janet/jaylib.so: undefined symbol: janet_getkeyword
  in native [src/core/corelib.c] on line 314
  in native-loader [boot.janet] on line 2622, column 40
  in require-1 [boot.janet] (tailcall) on line 2645, column 18
```
When running a binary built by `jpm build`.

**Comment by sogaiu** [comment]
Sorry for the confusion.

IIUC, the last 2 comments related to using `require` and loading `.so` from the compiled binary are not an error and are unrelated to the original issue.

That kind of thing won't work with the latest release of janet and the older jpm either.

**Comment by sogaiu** [comment]
It may be that [tweaking janet's recent `gensym` implementation](https://github.com/janet-lang/janet/issues/753) will take care of this issue.

**Comment by saikyun** [comment]
I tried sogaiu's fix, and it works for me. :)

**Comment by sogaiu** [comment]
It looks like https://github.com/janet-lang/janet/commit/a78cbd91dad1066ec82c31cb74b6c4bf2ea44d1b addressed https://github.com/janet-lang/janet/issues/753.

Perhaps this issue can be closed?

**Comment by saikyun** [comment]
Yup, works now. :)
