### ISSUE TITLE
The `--janet` flag is ignored

### ISSUE THREAD

**Issue by pyrmont** [janet-lang/jpm#23]
jpm provides a `--janet` flag that, to quote the help, sets:

```
The path or command name of the Janet binary used when spawning janet subprocesses
```

Regardless of the value passed to `--janet`, this doesn't happen. I think the problem is on line 73:

https://github.com/janet-lang/jpm/blob/c2be9143201154c2b068f954474f1e0983f81189/jpm/cli.janet#L70-L75

**Comment by bakpakin** [comment]
I guess we should probably only set this then if it is not already set. That said, this is a config variable that is not really meant to be used by the command line, and to be mainly used in a config file. It is just that all config variables can also be used at the command line as well as set in the config file.
