### ISSUE TITLE
jpm library

### ISSUE THREAD

**Issue by pepe** [janet-lang/jpm#24]
I want to use jpm as a library, for example, `pm/jpm`. But when I add jpm into `:dependencies` in `project.janet` `jpm -l deps` fails with:

```
No existing config found, use the jpm bootstrap script to generate a config and install
  in _thunk [./project.janet] (tailcall) on line 25, column 5
```

Are we able to mitigate this and install only sources?

**Comment by bakpakin** [comment]
Did you try installing jpm manually with the bootstrap process first? It should then install correctly the second time without a config.

**Comment by bakpakin** [comment]
Ok, as of c43519301fcaefc0c957c0720b8a9b6118551d90, you should now be able to use jpm as a dependency pretty seamlessly - if being installed to a new tree by another jpm, it should behave as you would expect mostly.
