### ISSUE TITLE
Integration with makefile?

### ISSUE THREAD

**Issue by glyh** [janet-lang/jpm#3]
There's already some existing libraries with a exisiting build tool(makefile). I don't want to create a whole bunch of new things in jpm. Is there a way that I can just extend the existing makefile so that I don't need to write everything again?

**Comment by glyh** [comment]
Or, is it just enough to add janet.h and janet.c, generating a .so file enough?

**Comment by bakpakin** [comment]
I'm not really sure exactly what you mean, do you want to build a library for Janet, or embed Janet into an application? You can add janet.h and janet.c to a project and ignore jpm entirely, but janet libraries that are written for jpm will have to be translated if you want to embed in a Makefile.

**Comment by bakpakin** [comment]
Of course, you can also call `jpm` from `make`, and you can call `make` from `jpm`.
