### ISSUE TITLE
bootstrap on windows: manuals are copied to /usr/local/share/man/man1 which is an illegal path

### ISSUE THREAD

**Issue by kamisori** [janet-lang/jpm#46]
maybe nonexisting/illegal paths could be fixed by the user interactively

or perhaps in case (= (os/which) :windows) manpages could be copied into a janet subfolder like the Library, docs, C, bin folders

**Comment by brifdva** [comment]
As an option, it may be fixed by adding env variable JANET_MANPATH value (path to /docs folder where Janet is installed) manually or with Janet msi
All other paths are generated with these like variables
