### ISSUE TITLE
Update all installed packages

### ISSUE THREAD

**Issue by tupini07** [janet-lang/jpm#52]
It would be great to have a way to easily update all installed packages. This can more or less already be done by doing something like 

```bash
jpm list-installed | xargs -I _ sudo jpm install _
```

However, this only works to update dependencies which are themselves listed in `pkgs.janet` (those in the [official package listing](https://github.com/janet-lang/pkgs)), but not for those packages that are only possible to install directly via git (for example: `jpm install https://github.com/sogaiu/jandent`).

Should be pretty easy to implement, just go through the files in the `.manifest` dir and call `install` for each of them. Although I might not be considering some potential issues

**Comment by bakpakin** [comment]
Added the 'update-installed` command to address this. Note that there is still some question about semantics here, especially when installing some packages from the "latest master", vs a specific tag. JPM only tracks that specific git commit installed, not what the user requested to be installed. So this may update packages that a user requested to be a specific tag. Still, I think for version pinned dependencies one should use a lockfile.

**Comment by tupini07** [comment]
That's great! and yes, I agree with the fact that pinned dependencies should use a lockfile. Also, I imagine globally installed packages would normally be binaries, so one normally wants to keep those up to date :)

Tagging the commit here just in case anyone is interested c886d61d170194c8e6a605658a17a078b6ab546a

Closing this issue
