### ISSUE TITLE
Add documentation to generated mendoza files

### ISSUE THREAD

**Issue by pepe** [janet-lang/jpm#58]
In my opinion, as jpm matures, it would be great to add more documentation to the `content/` folder, as in other projects (mendoza, jhydro ..). At least transplant and expand the index with the information we already have at https://janet-lang.org/docs/jpm.html and in  `README.md` of this repository. 

Then I would like to document cgen. I see it as one of the undiscovered gems in our ecosystem, which needs mostly more eyes and hands to get polished.

Please let me know if it sounds reasonable to you @bakpakin.

**Comment by Techcable** [comment]
Yes please!

I did not know about `cgen` until just recently 😄 

I would love to help contributing to docs, as I think that's one of the most important things the project needs....

**Comment by sogaiu** [comment]
It looks like in the 1.25.1 [1] version of the docs, there are [some more detailed jpm docs](https://janet-lang.org/1.25.1/api/jpm/index.html) (including some [cgen bits](https://janet-lang.org/1.25.1/api/jpm/cgen.html)).

@pepe Is this close to what you had in mind originally?

---

[1] According to the CHANGELOG, [Janet 1.25.1 came out in 2022-10](https://github.com/janet-lang/janet/blob/master/CHANGELOG.md#1251---2022-10-29).

**Comment by sogaiu** [comment]
The original posting has:

> At least transplant and expand the index with the information we already have at https://janet-lang.org/docs/jpm.html and in README.md of this repository.

Was curious whether you think the current state is close to this.

**Comment by pepe** [comment]
Thank you, I will look into it a little bit deeper on Thu.
