### ISSUE TITLE
No subcommand to create project with `create-executable`

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/jpm#74]
As noted in [this discussion](https://github.com/janet-lang/janet/discussions/1054#discussioncomment-6051809):

> In my view to create an executable should be the standard template for new-project

I agree that it would be nice for there to be some convenient way to create a new project that by default has an appropriate `create-executable` form in it.

I don't know whether that should be `new-project`, hence this issue instead of a PR.

**Comment by pepe** [comment]
I had the same thought when reading the discussion.

**Comment by sogaiu** [comment]
I guess one relatively simple idea would be another subcommand like `new-exe-project` or `new-project-with-exe`.

**Comment by MarcusE1W** [comment]
How about `new-exec` or `new-executable` ?

**Comment by sogaiu** [comment]
Yeah, may be those are nicely shorter names, perhaps fitting for the situation of quickly wanting to make a small executable :)

Though with such names I might expect a `project.janet` file that has content without `declare-source`, i.e. like:

```janet
(declare-project
  :name "fun"
  :description "Nice name"
  :version "0.0.0")

(declare-executable
  :name "fun"
  :entry "fun/init.janet")
```

**Comment by sogaiu** [comment]
On a side note, the file [`scaffold.janet`](https://github.com/janet-lang/jpm/blob/af002e6e61110eb89a46d881eb75eb86556eee81/jpm/scaffold.janet) code seems to have some "Python PEP292" templating features in it.  I wonder if something based on that would be a good addition to spork...

Anyway, I'll see if I can put together a draft PR using the name `new-exe` (although that kind of seems Windows-centric, I think `new-executable` is too long and I think one might easily forget the `c` at the end of `new-exec`).  Another name can replace that if discussion indicates there is a better choice.

**Comment by sogaiu** [comment]
#75 has been created.
