### ISSUE TITLE
Unexpected behavior with [un]installing global pkgs

### ISSUE THREAD

**Issue by pepe** [janet-lang/jpm#9]
I found that with the new separate `jpm` command, I cannot uninstall global packages. For some,  spork, for example, the solution is to install the package again and then uninstall it. For some others, miniz, for example, this does not work either.

**Comment by pepe** [comment]
I can reproduce this behavior on another system as well. There I tried to remove /usr/local/lib/janet and fresh install janet and jpm from source with the same result. I will try to investigate more later and come back with what I have found.

**Comment by pepe** [comment]
So only culprit I was able to find with my limited knowledge of the whole system is that native modules are found in `module/cache` at https://github.com/janet-lang/jpm/blob/cf6086ae3b282046141fd7b6fbd1d08edcb85fdd/jpm/cc.janet#L284 and that the cache is populated with the global native modules only.

**Comment by sogaiu** [comment]
FWIW, I tried with both spork and janet-miniz and here (Manjaro Linux) it seemed to work ok.

I don't have things installed under `/usr/local` though.

I can try in a VM for a `/usr/local` installation.

**Comment by sogaiu** [comment]
I didn't notice any difference -- it was with a VM running Manjaro Linux though.

May be it depends on the distribution?

**Comment by pepe** [comment]
The second systém i have used is also Manjaro. I guess it is something with my systems installation being old. I will try to clean it up and do fresh install thank you for testing @sogaiu. I am closing this as it seems to be user error.
