### ISSUE TITLE
Failed bootstrap install: No such file or directory on default Debian 12

### ISSUE THREAD

**Issue by lescx** [janet-lang/jpm#90]
I have been trying to install jpm on my Debian 12 dev machine. I'm a complete Janet noob, so if you need more information, let me know.

```shell
╭─[~/.local/repo/jpm] [ꨒ  master]
╰──╼sudo janet bootstrap.janet
destdir:
Using install prefix: /usr/local
binpath: /usr/local/bin
libpath: /usr/local/lib
manpath: /usr/local/share/man/man1
headerpath: /usr/local/include/janet
modpath: (default to JANET_PATH at runtime)
Setting package listing: https://github.com/janet-lang/pkgs.git
Running jpm to self install...
error: ("janet" "jpm/cli.janet" "install"): No such file or directory
  in os/execute [src/core/os.c] on line 1377
  in do-bootstrap [bootstrap.janet] on line 14, column 3
  in _thunk [bootstrap.janet] (tailcall) on line 26, column 1
```

## Steps to reproduce

1. Install Debian (duh)
2. Clone repo
3. cd into repo
4. `sudo janet bootstrap.janet`
5. No profit

## Expected behaviour

Profit.

---

* OS: Debian 12 (bookworm)
* janet -v: 1.34.0-f92f3eb
* `build-essential`, `make`, `gcc` and `clang` are installed, if required.

**Comment by bakpakin** [comment]
Where is Janet installed? I.e. 'which janet'

**Comment by lescx** [comment]
```
$ which janet
/home/luca/.local/bin/janet/bin/janet
$ path | grep janet
/home/luca/.local/bin/janet/bin
```

**Comment by bakpakin** [comment]
Your are trying to use a local install of Janet and a system install of JPM - you don't need sudo. When building and installing Janet, did you try 'make install-jpm-git'? This will put JPM in the right place.

**Comment by lescx** [comment]
Thank you for pointing this out. Without sudo the same issue occurred.
I should have said that I installed Janet using the prebuilt GitHub release. I built Janet from sourcehut - I'm happily using jpm now. :)

Closed because I didn't read the documentation properly.

**Comment by sogaiu** [comment]
For future visitors there are [some related official docs](https://janet-lang.org/docs/index.html#Non-root-install-(macOS-and-Unix-like)).
